config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount API::Root, at: '/'
  mount Sidekiq::Web, at: '/jobs'
  mount GrapeSwaggerRails::Engine, at: '/swagger'

  ActiveAdmin.routes(self)
  root                                 to: 'admin/dashboard#index'
  get    'admin/login',                to: 'application#login',         as: 'login'
  delete 'admin/logout',               to: 'application#logout',        as: 'destroy_user_session'
  get    'admin/logout',               to: 'application#logout'

  post   'admin/authenticate',         to: 'application#authenticate',  as: 'authenticate'
  match	 'debug',                      to: 'application#debug',         as: 'debug', via: [:get, :post]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def authenticate_user!
    return if session[:user]&.[]('admin') == true
    flash[:alert] = 'User authorization reuquired'
    redirect_to login_path
  end

  def access_denied(x)
    reset_session
    redirect_to :root
  end

  def logout
    reset_session
    redirect_to :root
  end

  def current_user
    User.find session[:current_user_id] rescue nil
  end

  def authenticate
    # if !verify_recaptcha(action: 'login', minimum_score: 0.6)
    #   @error = t('errors.messages.recaptcha')
    #   render :login
    #   return
    # end
    user = User.find_by_email_password(email: params[:user][:email].downcase, password: params[:user][:password])
    if user
      session[:user] = {'admin' => true}
      session[:current_user_id] = user.id
      redirect_to admin_dashboard_path
    else
      @error = 'Sign in failed'
      render :login
    end
  end

  def debug
    @error_id = params['error_id'] || 'last_error'
    @exception = ErrorLogger.debug @error_id
    if @exception.blank?
      flash.now[:alert] = "Exception #{@error_id} not find in storage"
    end
  end
  private
  def set_locale
    I18n.locale = 'en'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_show(model: nil, attribute: nil, file: nil, height: 150)
    if file&.url.present?
      image_tag file.url, style: "height:#{height}px;width:auto;"
      return
    end
    return unless model&.send(attribute).url.present?
    image_tag model.send(attribute).url, style: "height:#{height}px;width:auto;"
  end

  def show_slider(model, attribute: :files, height: 120)
    return unless model.send(attribute).present?
    html = Arbre::Context.new do
      div class: 'slider' do
        model.send(attribute).each do |file|
          img src: file.url, style: "height:#{height}px;width:auto;"
        end
        div class: 'previewer'
      end
    end
    raw html
  rescue
    nil
  end
end

app/views/application/debug.slim
#background
  form#debug-form url=debug_url
    input type='text' name='error_id' placeholder='Error identifier' value=@error_id
    button.button type='submit' Inspect
  h1.error = @error_id
  #debug
    - if @error_id.present? && @exception.present?
      #message.error = @exception[:message]
      #time = "Occured at: #{@exception[:time]}\n" rescue nil
      #trace
        - if @exception.present?
          - @exception[:backtrace].each do |line|
            - root = Rails.root.to_s
            - if line.include?(root)
              - path = line.gsub(root, '').match(/.+:\d+/)[0][1..-1]
              a class='error' href="jetbrains://rubymine/navigate/reference?project=telegram_analytic&path=#{path}:1" =line
            - else
              div =line

app/views/application/login.slim
#background
  #auth-form-wrapper
    #logo
      = raw image_tag('logo.svg')
    #auth-form
      h1 = t('user.sign_in_form.title')
      = form_for(User.new, as: :user, url: authenticate_path) do |f|
        #auth-inputs
          = f.text_field :email, placeholder: t('user.sign_in_form.email'), autofocus: true
          = f.password_field :password, placeholder: t('user.sign_in_form.password')
        .error = @error
        button.button type='submit' = t('user.sign_in_form.button')
  #app-version = "VERSION INFO: #{$VERSION}"